<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\LingFan.Media.Abstractions\LingFan.Media.Abstractions.csproj" />
    <ProjectReference Include="..\..\Infrastructure\LingFan.Media.Extensions\LingFan.Media.Extensions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <!-- AOT：[LibraryImport] 源生成器需 AllowUnsafeBlocks（SYSLIB1062） -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
