<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\LingFan.Media.Abstractions\LingFan.Media.Abstractions.csproj" />
		<ProjectReference Include="..\LingFan.Media.Extensions\LingFan.Media.Extensions.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
	</PropertyGroup>

</Project>
