<#
.SYNOPSIS
    Convert precompiled SPIR-V (.spv) binaries into a C# byte-array source file.

.DESCRIPTION
    Reads all *.spv under $InputDir and generates $OutputFile (Shaders.g.cs),
    containing internal static readonly byte[] constants. Runtime has zero reflection
    and zero Assembly resource access, so it is NativeAOT / trim safe. The file is
    produced by the MSBuild target during build and compiled into the assembly, then
    shipped in the NuGet package; downstream consumers never re-run any tool.

.PARAMETER InputDir
    Directory holding the *.spv files (typically Shaders/).

.PARAMETER OutputFile
    Path of the generated .cs file (typically obj/<Config>/<Tfm>/Shaders.g.cs).
#>
param(
    [Parameter(Mandatory = $true)] [string] $InputDir,
    [Parameter(Mandatory = $true)] [string] $OutputFile
)

$ErrorActionPreference = 'Stop'

$spvFiles = Get-ChildItem -Path $InputDir -Filter *.spv | Sort-Object Name
if ($spvFiles.Count -eq 0) {
    throw "No .spv files found in $InputDir"
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated>')
$lines.Add('// Generated by generate-shader-bytes.ps1 from precompiled SPIR-V (.spv). Do not edit.')
$lines.Add('// Runtime: zero reflection, zero Assembly resource access. NativeAOT / trim safe.')
$lines.Add('// Regenerate: recompile .vert/.frag to .spv via glslang, then the MSBuild target runs this at build time.')
$lines.Add('// </auto-generated>')
$lines.Add('namespace LingFan.Media.GPUShare.Vulkan;')
$lines.Add('')
$lines.Add('internal static class EmbeddedShaders')
$lines.Add('{')

$totalBytes = 0
foreach ($f in $spvFiles) {
    $base = $f.BaseName
    $ident = $base -replace '[^A-Za-z0-9]', '_'
    $bytes = [System.IO.File]::ReadAllBytes($f.FullName)
    # SPIR-V magic = 0x07230203 (little-endian file layout: 03 02 23 07). Reject non-SPIR-V input early
    # so a corrupt or stale file fails the build with a clear message instead of embedding garbage.
    if ($bytes.Length -lt 4 -or $bytes[0] -ne 0x03 -or $bytes[1] -ne 0x02 -or $bytes[2] -ne 0x23 -or $bytes[3] -ne 0x07) {
        throw "File $($f.Name) is not a valid SPIR-V module (bad magic number). Recompile from GLSL via 'glslang -V'."
    }
    $totalBytes += $bytes.Length
    $lines.Add("    /// <summary>Precompiled SPIR-V module: $($f.Name) ($($bytes.Length) bytes).</summary>")
    $lines.Add("    internal static readonly byte[] $ident = new byte[]")
    $lines.Add('    {')
    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        $end = [Math]::Min($i + 15, $bytes.Length - 1)
        $slice = $bytes[$i..$end]
        $hex = ($slice | ForEach-Object { '0x{0:X2}' -f $_ }) -join ', '
        $lines.Add("        $hex,")
    }
    $lines.Add('    };')
    $lines.Add('')
}

$lines.Add('}')

$outDir = Split-Path -Parent $OutputFile
if (-not [System.IO.Directory]::Exists($outDir)) {
    [System.IO.Directory]::CreateDirectory($outDir) | Out-Null
}
[System.IO.File]::WriteAllText($OutputFile, ($lines -join [Environment]::NewLine) + [Environment]::NewLine, [System.Text.Encoding]::UTF8)
Write-Host "[GEN-SHADERS] Generated $OutputFile ($($spvFiles.Count) SPIR-V module(s), $totalBytes bytes total)"
