<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\LingFan.Media.Abstractions\LingFan.Media.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <!-- GStreamer 后端目前绝对不提供（非标准、处于不支持队列，后续可能提供）。 -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
