<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <RootNamespace>LingFan.Media.AvaloniaTools</RootNamespace>
    <TargetFramework>net10.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" Version="12.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LingFan.Media.AvaloniaTools\LingFan.Media.AvaloniaTools.csproj" />
  </ItemGroup>
</Project>
